# Generated by Django 5.2.5 on 2025-09-03 09:40

import authors.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_deleted_author_profile_author_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(validators=[authors.models.validators.validate_age], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Если False - автор активен. Если True - автора больше нет в списке доступных', verbose_name='Удален ли автор'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль'),
        ),
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг автора'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('publishing_date', models.DateField(verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authors.author', verbose_name='Автор')),
            ],
        ),
    ]
