# Generated by Django 5.2.5 on 2025-09-04 07:49

import authors.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_category_library_book_category_book_libraries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('date_of_birth', models.DateField(validators=[authors.models.validators.validate_age])),
                ('role', models.CharField(max_length=20, verbose_name='Роль')),
                ('active', models.BooleanField(default=True)),
                ('libraries', models.ManyToManyField(related_name='members', to='authors.library')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.member'),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
