# Generated by Django 5.2.5 on 2025-09-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_member_alter_book_publisher_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique_for_date='created_at', verbose_name='Название')),
                ('body', models.TextField(verbose_name='Текст поста')),
                ('moderated', models.BooleanField(default=False, verbose_name='Промодерировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='authors.member')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='authors.library')),
            ],
        ),
    ]
