# Generated by Django 5.2.5 on 2025-09-04 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(verbose_name='Дата взятия книги')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='authors.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='authors.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='authors.member')),
            ],
        ),
    ]
