# Generated by Django 5.2.5 on 2025-09-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='authors.author', verbose_name='Автор'),
        ),
    ]
